baseURL = 'https://jamienoel.com/'
locale = 'en-US'
title = 'JH Noel'
theme = 'hugo-flex'

[params]
  description = "Personal site of JH Noel"
  author = { name = "JH Noel" }
  copyright = "(c) James H Noel 2026"
  footer = "(c) James H Noel 2026 · <a href='https://github.com/jhnoel'>GitHub</a> · <a href='https://linkedin.com/in/jhnoel'>LinkedIn</a>"
  color = "teal"
  width = "42rem"
  favicon = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
