baseURL = 'https://jamienoel.com/'
locale = 'en-US'
title = 'Jamie Noel'
theme = 'etch'
enableRobotsTXT = true
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    title = 'Posts'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    title = 'About'
    url = '/about/'
    weight = 20

[permalinks]
  posts = '/posts/:slug/'

[params]
  description = "Personal site of Jamie Noel"
  copyright = "(c) James H Noel 2026"
  dark = "auto"
  highlight = true
  mainSections = ["posts"]

[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
